name: Active Heating Manager
version: 0.5.0
slug: active_heating_manager
description: Smart heating management for Home Assistant
url: https://github.com/BenWolstencroft/home-assistant-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
map:
  - config:rw
homeassistant_api: true
hassio_api: true
gpio: false
apparmor: false
options:
  debug_logging: false
  trv_entities: []
  boiler_entity: ""
  boiler_mode: "thermostat"
  manual_on_temperature: 21
  manual_off_temperature: 14
  check_valve_state: true
  polling_interval: 300
schema:
  debug_logging: bool
  trv_entities: [str?]
  boiler_entity: str?
  boiler_mode: list(thermostat|toggle)
  manual_on_temperature: int(15,35)
  manual_off_temperature: int(5,20)
  check_valve_state: bool
  polling_interval: int(10,3600)
