name: Active Heating Manager
version: 0.8.1
slug: active_heating_manager
description: Smart heating management for Home Assistant
url: https://github.com/BenWolstencroft/home-assistant-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
map:
  - config:rw
homeassistant_api: true
hassio_api: true
gpio: false
apparmor: false
services:
  - mqtt:want
options:
  debug_logging: false
  trv_entities: []
  boiler_entity: ""
  boiler_mode: "thermostat"
  manual_on_temperature: 21
  manual_off_temperature: 14
  check_valve_state: true
  use_dynamic_temperature: true
  polling_interval: 300
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  debug_logging: bool
  trv_entities: [str?]
  boiler_entity: str?
  boiler_mode: list(thermostat|toggle)
  manual_on_temperature: int(15,35)
  manual_off_temperature: int(5,20)
  check_valve_state: bool
  use_dynamic_temperature: bool
  polling_interval: int(10,3600)
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_password: password?
