name: Argon ONE Active Cooling
version: 1.0.5
slug: argon_one_active_cooling
description: Temperature-based fan control for Argon ONE v5 case
url: https://github.com/BenWolstencroft/home-assistant-addons
arch:
  - armhf
  - armv7
  - aarch64
init: false
startup: application
boot: auto
map:
  - config:rw
homeassistant_api: true
hassio_api: true
gpio: true
apparmor: false
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
  - /dev/i2c-21
  - /dev/i2c-22
  - /dev/i2c-23
  - /dev/i2c-24
  - /dev/i2c-25
  - /dev/i2c-26
options:
  temp_unit: C
  cpu_fan_temps:
    - temp: 55
      speed: 30
    - temp: 60
      speed: 55
    - temp: 65
      speed: 100
  check_interval: 60
  debug_logging: false
schema:
  temp_unit: list(C|F)
  cpu_fan_temps:
    - temp: int(30,85)
      speed: int(0,100)
  check_interval: int(10,300)
  debug_logging: bool
